### ISSUE TITLE
Cassandra query is not working

### ISSUE THREAD

**Issue by anthonyray** [anthonyray/japan-tsunami#1]
Hello guys, 

j'ai l'impression que la requête Cassandra ne marche pas ! 
Je l'ai appliquée au dataset de 1GB, voici ma requête : 

```
SELECT * FROM japtest.bigtable WHERE token(timestamp,latitude,longitude)>=token('2015-01-19',135.0,34.0) and token(timestamp,latitude,longitude)<token('2015-01-20',136.0,35.0);
```

La requête passe, mais voici un extrait de résultats étranges : 

```
 2015-01-26 15:02:47+0000 |   141.39 |     43.51 |  Sap_15 | 819516
```

On est en dehors des dates, mauvaise longitude, et mauvaise latitude  ... La requête ci-dessus me renvoie plein d'erreurs comme ça ... 
Je me trompe quelque part ou alors la requete est fausse ?

**Comment by franblas** [comment]
Manifestement Cassandra ne filtre rien du tout... Apres test sur une autre base avec seulement le timestamp en clé primaire, les timestamps ne sont pas interpretes du tout comme il faut... 
Je test en local

**Comment by franblas** [comment]
https://github.com/anthonyray/japan-tsunami/blob/master/Cassandra/cassandraTest.py#L83
La fonction alertPhones() fonctionne mais il semblerait en effet que la requete Cassandra qui est censé filtrer ne marche pas comme prévu

**Comment by franblas** [comment]
Finally it's okay.
